import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/base/Navbar";
import Sidebar from "@/src/components/base/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-pale flex h-[100vh]  flex-col`}
      >
        <Navbar />
        <div className="flex  flex-1"><Sidebar />
          <div className="p-4  w-full">
            {children}
          </div></div>
      </body>
    </html>
  );
}
